#include <pybind11/pybind11.h>

#include "../sdk/LEPTON_ErrorCodes.h"

namespace py = pybind11;

PYBIND11_MODULE(lepton_error_codes, handle){
    handle.doc() = "Contains the Lepton SDK Error Codes";

    py::enum_<LEP_RESULT>(handle,"LEP_RESULT")
        .value("LEP_OK",LEP_RESULT::LEP_OK)
        .value("LEP_COMM_OK",LEP_RESULT::LEP_COMM_OK)
        .value("LEP_ERROR",LEP_RESULT::LEP_ERROR)
        .value("LEP_NOT_READY",LEP_RESULT::LEP_NOT_READY)
        .value("LEP_RANGE_ERROR",LEP_RESULT::LEP_RANGE_ERROR)
        .value("LEP_CHECKSUM_ERROR",LEP_RESULT::LEP_CHECKSUM_ERROR)
        .value("LEP_BAD_ARG_POINTER_ERROR",LEP_RESULT::LEP_BAD_ARG_POINTER_ERROR)
        .value("LEP_DATA_SIZE_ERROR",LEP_RESULT::LEP_DATA_SIZE_ERROR)
        .value("LEP_UNDEFINED_FUNCTION_ERROR",LEP_RESULT::LEP_UNDEFINED_FUNCTION_ERROR)
        .value("LEP_FUNCTION_NOT_SUPPORTED",LEP_RESULT::LEP_FUNCTION_NOT_SUPPORTED)
        .value("LEP_OTP_WRITE_ERROR",LEP_RESULT::LEP_OTP_WRITE_ERROR)
        .value("LEP_OTP_READ_ERROR",LEP_RESULT::LEP_OTP_READ_ERROR)
        .value("LEP_OTP_NOT_PROGRAMMED_ERROR",LEP_RESULT::LEP_OTP_NOT_PROGRAMMED_ERROR)
        .value("LEP_ERROR_I2C_BUS_NOT_READY",LEP_RESULT::LEP_ERROR_I2C_BUS_NOT_READY)
        .value("LEP_ERROR_I2C_BUFFER_OVERFLOW",LEP_RESULT::LEP_ERROR_I2C_BUFFER_OVERFLOW)
        .value("LEP_ERROR_I2C_ARBITRATION_LOST",LEP_RESULT::LEP_ERROR_I2C_ARBITRATION_LOST)
        .value("LEP_ERROR_I2C_BUS_ERROR",LEP_RESULT::LEP_ERROR_I2C_BUS_ERROR)
        .value("LEP_ERROR_I2C_NACK_RECEIVED",LEP_RESULT::LEP_ERROR_I2C_NACK_RECEIVED)
        .value("LEP_ERROR_I2C_FAIL",LEP_RESULT::LEP_ERROR_I2C_FAIL)
        .value("LEP_DIV_ZERO_ERROR",LEP_RESULT::LEP_DIV_ZERO_ERROR)
        .value("LEP_COMM_PORT_NOT_OPEN",LEP_RESULT::LEP_COMM_PORT_NOT_OPEN)
        .value("LEP_COMM_INVALID_PORT_ERROR",LEP_RESULT::LEP_COMM_INVALID_PORT_ERROR)
        .value("LEP_COMM_RANGE_ERROR",LEP_RESULT::LEP_COMM_RANGE_ERROR)
        .value("LEP_ERROR_CREATING_COMM",LEP_RESULT::LEP_ERROR_CREATING_COMM)
        .value("LEP_ERROR_STARTING_COMM",LEP_RESULT::LEP_ERROR_STARTING_COMM)
        .value("LEP_ERROR_CLOSING_COMM",LEP_RESULT::LEP_ERROR_CLOSING_COMM)
        .value("LEP_COMM_CHECKSUM_ERROR",LEP_RESULT::LEP_COMM_CHECKSUM_ERROR)
        .value("LEP_COMM_NO_DEV",LEP_RESULT::LEP_COMM_NO_DEV)
        .value("LEP_TIMEOUT_ERROR",LEP_RESULT::LEP_TIMEOUT_ERROR)
        .value("LEP_COMM_ERROR_WRITING_COMM",LEP_RESULT::LEP_COMM_ERROR_WRITING_COMM)
        .value("LEP_COMM_ERROR_READING_COMM",LEP_RESULT::LEP_COMM_ERROR_READING_COMM)
        .value("LEP_COMM_COUNT_ERROR",LEP_RESULT::LEP_COMM_COUNT_ERROR)
        .value("LEP_OPERATION_CANCELED",LEP_RESULT::LEP_OPERATION_CANCELED)
        .value("LEP_UNDEFINED_ERROR_CODE",LEP_RESULT::LEP_UNDEFINED_ERROR_CODE)
        .export_values();
}