# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/mnt/hdd/iqbal/kuliah/TA/PA2/pa_deploy/client_program/resources/ui/AuthWidget.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_AuthWidget(object):
    def setupUi(self, AuthWidget):
        AuthWidget.setObjectName("AuthWidget")
        AuthWidget.resize(1006, 582)
        AuthWidget.setAutoFillBackground(True)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(AuthWidget)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem)
        self.label = QtWidgets.QLabel(AuthWidget)
        self.label.setObjectName("label")
        self.verticalLayout_3.addWidget(self.label, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.le_password = QtWidgets.QLineEdit(AuthWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.le_password.sizePolicy().hasHeightForWidth())
        self.le_password.setSizePolicy(sizePolicy)
        self.le_password.setMinimumSize(QtCore.QSize(300, 0))
        self.le_password.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.le_password.setEchoMode(QtWidgets.QLineEdit.Password)
        self.le_password.setObjectName("le_password")
        self.verticalLayout_3.addWidget(self.le_password, 0, QtCore.Qt.AlignHCenter)
        self.horizontalWidget = QtWidgets.QWidget(AuthWidget)
        self.horizontalWidget.setObjectName("horizontalWidget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalWidget)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.pb_cancel = QtWidgets.QPushButton(self.horizontalWidget)
        self.pb_cancel.setObjectName("pb_cancel")
        self.horizontalLayout_2.addWidget(self.pb_cancel)
        self.pb_login = QtWidgets.QPushButton(self.horizontalWidget)
        self.pb_login.setObjectName("pb_login")
        self.horizontalLayout_2.addWidget(self.pb_login)
        self.verticalLayout_3.addWidget(self.horizontalWidget, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem1)

        self.retranslateUi(AuthWidget)
        QtCore.QMetaObject.connectSlotsByName(AuthWidget)

    def retranslateUi(self, AuthWidget):
        _translate = QtCore.QCoreApplication.translate
        AuthWidget.setWindowTitle(_translate("AuthWidget", "Form"))
        self.label.setText(_translate("AuthWidget", "Password"))
        self.le_password.setPlaceholderText(_translate("AuthWidget", "Insert Password Here"))
        self.pb_cancel.setText(_translate("AuthWidget", "Cancel"))
        self.pb_login.setText(_translate("AuthWidget", "Login"))
