# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/mnt/hdd/iqbal/kuliah/TA/PA2/pa_deploy/client_program/resources/ui/TableWidget.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_TableWidget(object):
    def setupUi(self, TableWidget):
        TableWidget.setObjectName("TableWidget")
        TableWidget.resize(1006, 582)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(TableWidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.tableWidget = QtWidgets.QTableWidget(TableWidget)
        self.tableWidget.setRowCount(2)
        self.tableWidget.setColumnCount(4)
        self.tableWidget.setObjectName("tableWidget")
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        self.tableWidget.horizontalHeader().setVisible(True)
        self.tableWidget.horizontalHeader().setCascadingSectionResizes(False)
        self.tableWidget.horizontalHeader().setDefaultSectionSize(105)
        self.tableWidget.horizontalHeader().setMinimumSectionSize(27)
        self.tableWidget.horizontalHeader().setSortIndicatorShown(False)
        self.tableWidget.horizontalHeader().setStretchLastSection(True)
        self.tableWidget.verticalHeader().setVisible(False)
        self.verticalLayout_2.addWidget(self.tableWidget)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pb_back = QtWidgets.QPushButton(TableWidget)
        self.pb_back.setObjectName("pb_back")
        self.horizontalLayout.addWidget(self.pb_back)
        self.pb_create = QtWidgets.QPushButton(TableWidget)
        self.pb_create.setObjectName("pb_create")
        self.horizontalLayout.addWidget(self.pb_create)
        self.pb_update = QtWidgets.QPushButton(TableWidget)
        self.pb_update.setObjectName("pb_update")
        self.horizontalLayout.addWidget(self.pb_update)
        self.pb_delete = QtWidgets.QPushButton(TableWidget)
        self.pb_delete.setObjectName("pb_delete")
        self.horizontalLayout.addWidget(self.pb_delete)
        self.verticalLayout_2.addLayout(self.horizontalLayout)

        self.retranslateUi(TableWidget)
        QtCore.QMetaObject.connectSlotsByName(TableWidget)

    def retranslateUi(self, TableWidget):
        _translate = QtCore.QCoreApplication.translate
        TableWidget.setWindowTitle(_translate("TableWidget", "Form"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("TableWidget", "Id"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("TableWidget", "Name"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("TableWidget", "Id Type"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("TableWidget", "Role"))
        self.pb_back.setText(_translate("TableWidget", "Back"))
        self.pb_create.setText(_translate("TableWidget", "Create"))
        self.pb_update.setText(_translate("TableWidget", "Update"))
        self.pb_delete.setText(_translate("TableWidget", "Delete"))
